### 02-02

In [1]:
import numpy as np

t = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(t)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
print("Rank of t:", t.ndim)
print("Shape of t:",t.shape)

Rank of t: 1
Shape of t: (10,)


In [3]:
t = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print("Rank of t:", t.ndim)
print("Shape of t:", t.shape)

Rank of t: 2
Shape of t: (3, 3)


In [5]:
import torch

t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [6]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [7]:
print(t[0], t[2], t[4])

tensor(0.) tensor(2.) tensor(4.)


In [8]:
t = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
print(t)    

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [9]:
print(t.dim())
print(t.shape)
print(t.size())

2
torch.Size([3, 3])
torch.Size([3, 3])


In [10]:
print(t[1:,2])
print(t[-2:,0])

tensor([6., 9.])
tensor([4., 7.])


In [11]:
print(t[: , :-1])

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])


In [12]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])

print(m1 + m2)

tensor([5., 5.])


In [13]:
#Vector + scalar

m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [14]:
# 2 x 1 Vector + 1 x 2 Vector

m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])

print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [15]:
#행렬 곱

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1], [2]])


print(m1.matmul(m2))
print(m1.mul(m2))


tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


In [16]:
t = torch.FloatTensor([[1,2],[3,4]])

print(t)

print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [17]:
t = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])

print(t)

print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor(45.)
tensor([12., 15., 18.])
tensor([ 6., 15., 24.])
tensor([ 6., 15., 24.])


In [18]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)


In [19]:
print(ft)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [20]:
print(ft.shape)

torch.Size([2, 2, 3])


In [21]:
print(ft.view([-1,3]))  # 두번째 차원의 크기를 3으로로
print(ft.view([-1,3]).shape)  

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [22]:
print(ft.view([-1,1,3])) 
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [23]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [24]:
print(ft.squeeze())
print(ft.squeeze().shape)


tensor([0., 1., 2.])
torch.Size([3])


In [25]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [26]:
print(ft.unsqueeze(1))

tensor([[0.],
        [1.],
        [2.]])


In [27]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x,y], dim = 0))


tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [28]:
print(torch.cat([x,y], dim = 1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [29]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)


tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [30]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [31]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 02-03

In [36]:
# 함수와 클래스의 차이

# 함수로 덧셈기 구현

result = 0

def add(num):
    global result
    result += num
    return result

print(add(5))

5


In [38]:
# 함수 두개로 덧셈기 구현

result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(5))
print(add1(7))
print(add2(1))
print(add2(15))

5
12
1
16


In [ ]:
# class로 구현



class Calculator():
    def __init__(self): # 객체 생성 시 호출될 때 실행되는 초기화 함수. 이를 생성자라고 한다.
        self.result = 0 # 객체 생성 시 result가 0으로 초기화 됨 
    
    def add(self,num): # 객체를 생성 후 사용하는 함수
        self.result += num 
        return self.result

In [ ]:
cal1 = Calculator()
cal2 = Calculator()

print(cal1.add(3)) 
print(cal1.add(9))
print(cal2.add(6))
print(cal2.add(4))



6
15
7
11


In [43]:
class Calculator:
    def __init__(self):  # 생성자 (객체가 생성될 때 호출)
        self.result = 0   # 각 인스턴스마다 개별적으로 저장되는 값
    
    def add(self, num):
        self.result += num
        return self.result
    
    def subtract(self, num):
        self.result -= num
        return self.result
    
    def multiply(self, num):
        self.result *= num
        return self.result
    
    def divide(self, num):
        if num != 0:
            self.result /= num
        else:
            return "0으로 나눌 수 없습니다."
        return self.result


In [ ]:
# 기본 계산기 사용
cal1 = Calculator()
cal2 = Calculator()
print(cal1.add(10))  
print(cal1.multiply(2))  

print(cal2.add(50))
print(cal2.subtract(21))
print(cal2.divide(2))



10
20
50
29
14.5


In [46]:
class Calculator:
    result = 0  # 클래스 변수 (모든 인스턴스가 공유)

    def __init__(self):  # 생성자
        pass  # 아무것도 하지 않음
    
    def add(self, num):
        Calculator.result += num
        return Calculator.result
    
    def subtract(self, num):
        Calculator.result -= num
        return Calculator.result
    
    def multiply(self, num):
        Calculator.result *= num
        return Calculator.result
    
    def divide(self, num):
        if num != 0:
            Calculator.result /= num
        else:
            return "0으로 나눌 수 없습니다."
        return Calculator.result

# 테스트
calc1 = Calculator()
calc2 = Calculator()

print(calc1.add(10))  # 10
print(calc2.add(5))   # 15 (calc2도 같은 result를 공유)
print(calc1.multiply(2))  # 30 (공유된 result가 변경됨)
print(calc2.subtract(5))  # 25 (calc1과 calc2가 같은 값 공유)


10
15
30
25
